### ISSUE TITLE
Frame processor frame_enhancer could not be loaded

### ISSUE THREAD

**Issue by bence-t0th** [facefusion/facefusion-pinokio#11]
<<PINOKIO SHELL>> source /Users/xxx/pinokio/api/facefusion-pinokio.git/facefusion/env/bin/activate /Users/xxx/pinokio/api/facefusion-pinokio.git/facefusion/env && python run.py
[FACEFUSION.PROCESSORS.FRAME.CORE] Frame processor frame_enhancer could not be loaded
(env) <<PINOKIO SHELL>>

**Comment by ngoqquyen** [comment]
Reinstall

**Comment by henryruhs** [comment]
Should be a non issue in 2.4.0
