### ISSUE TITLE
the facefusion start button will not launch the process anymore

### ISSUE THREAD

**Issue by Akossimon** [facefusion/facefusion-pinokio#16]
the facefusion download into pinokio and facefusion launching etc  worked for a day ...  so facefusion worked for day.... then suddenly an hour ago  it doesnt start the "start" process anymore at all, although all has been set like before where it worked well.... would this here be the correct place to ask for help on this?  thanks

**Comment by henryruhs** [comment]
Use our Discord and stop opening support issues.
