### ISSUE TITLE
I'm keep having this issue

### ISSUE THREAD

**Issue by jsdavid88** [facefusion/facefusion-pinokio#17]
*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', ('CUDAExecutionProvider', {'cudnn_conv_algo_search': 'DEFAULT'})]
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-04-24 10:39:18.3717953 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\user\pinokio\bin\miniconda\envs\facefusion\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

**Comment by mohakchhaparwal** [comment]
I'm having the same issue. not sure why I've added lib and bin folders to System PATH. 
Please let me know if you find any solutions.

**Comment by mohakchhaparwal** [comment]
@henryruhs any solution for this?

**Comment by jsdavid88** [comment]
@mohakchhaparwal no found solution yet?

**Comment by mohakchhaparwal** [comment]
@jsdavid88 , I struggled a lot with many articles to solve this. I'm not a person from technical or coding background. However, after many hours of understanding I found a solution that worked for me. hope it would be helpful for you as well. let me explain:

As per my understanding, there are three possible causes for this error: 

1. You haven't installed the CUDA, cuDNN or TensorRT 
2. Even if you have them installed, they're not compatible with each other to work properly.
3. Even if they're compatible, then their (All three Items) /bin and /lib folders containing DLL files is not added to your PATH system environment variables.

**The Solution**

1. Install cuda_11.8.0_522.06_windows from [here](https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local) 
2. Install TensorRT-8.5.3.1.Windows10.x86_64.cuda-11.8.cudnn8.6 from [here
](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/8.5.3/zip/TensorRT-8.5.3.1.Windows10.x86_64.cuda-11.8.cudnn8.6.zip)
3. Install cudnn-windows-x86_64-8.6.0.163_cuda11-archive from [here](https://developer.nvidia.com/compute/cudnn/secure/8.6.0/local_installers/11.8/cudnn-windows-x86_64-8.6.0.163_cuda11-archive.zip)

You'll need to use python to prepare the environment and install the packages (see TensorRT [installation](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip) and cuDNN [installation](https://docs.nvidia.com/deeplearning/cudnn/latest/installation/windows.html).

Don't forget to install the onnx_graphsurgeon wheel packages while installing TensorRT. You must prepare the Python environment before installing onnx_graphsurgeon.

Once done, please add all the /Lib and /Bin folder to PATH System (same as explained in TensorRT installation page)

I found this ray of hope which is more clearly explained [here](https://zhuanlan.zhihu.com/p/659087539) (translate the page in English as it in Chinese originally)

Hope it'll help you to get it running. Please respond once you're good with it or any problem comes up.

**Comment by henryruhs** [comment]
Use Discord and stop opening support issues.
