### ISSUE TITLE
cuda installation failed while installing facefusion for pinokio

### ISSUE THREAD

**Issue by petrk94** [facefusion/facefusion-pinokio#22]
I think we have a bug here.
I tried several times to install Facefusion, all dependancies was installed, only cuda fails,

Pinokio Version 1.3.4
SCRIPT VERSION 1.5 - FaceFusion 2.6.1
the installer says, that the installation is completed, but it doesnt work. There is no further guiding in the installation how to proceed.

Im doing something wrong?

**Comment by henryruhs** [comment]
#
Please join [Discord](https://join.facefusion.io) for help.
