### ISSUE TITLE
why does windows detect ffmpeg.exe as a virus?

### ISSUE THREAD

**Issue by narsone** [facefusion/facefusion-pinokio#24]
In this path G:\IA\pinokio\bin\miniconda\Library\bin\ffmpeg.exe windows detects ffmpeg.exe as a virus = Trojan:Win32/Wacatac.B!ml. Can I trust in this file?

**Comment by TitasDas** [comment]
It should be fine. Usually opensource softwares are sometimes flagged. If you still want to check what's it doing to your system you can use a tool like [process explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer).

**Comment by TitasDas** [comment]
As additional precaution make sure you have downloaded/installed ffmpeg from its parent source. And this is probably happening because of the way it is being used in this project.

**Comment by narsone** [comment]
Thanks for the reply. It makes me feel quite comfortable.
