### ISSUE TITLE
No Cuda option for Execution Providers

### ISSUE THREAD

**Issue by TheBerserker07** [facefusion/facefusion-pinokio#29]
![image](https://github.com/user-attachments/assets/b2095fdc-e23c-47aa-82d3-835a31367d34)
I cannot find any CUDA option, I ran facefusion through pinokio, I have a rtx 3070ti

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.

**Comment by TheBerserker07** [comment]
says the discord link is invalid

**Comment by TheBerserker07** [comment]
it says, the link is invalid

**Comment by henryruhs** [comment]
https://discord.com/invite/facefusion-1141812857462341693
