### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by wteyn** [facefusion/facefusion-pinokio#7]
![p1](https://github.com/facefusion/facefusion-pinokio/assets/156513621/07f37054-dbf3-4a8b-9c74-85b3b5745717)
Error when installing any application on Windows in Pinokio. How to fix it?

**Comment by henryruhs** [comment]
Use Discord for help.

**Comment by wteyn** [comment]
> Пожалуйста, присоединяйтесь к нашему Discord за помощью. Мы здесь не оказываем поддержку.

The discord link is invalid. Can I have a new discord link?

**Comment by wteyn** [comment]
> Пожалуйста, присоединяйтесь к нашему Discord за помощью. Мы здесь не оказываем поддержку.

The discord link is invalid. Can I have a new discord link?

**Comment by henryruhs** [comment]
https://join.facefusion.io
